package com.comparisonOperator

import com.vivian.drools.entity.ComparisonOperatorEntity

/**
    当前规则文件用于测试drools提供的比较操作符
**/

// 测试比较操作符contains
rule "rule_comparison_contains"
    when
        ComparisonOperatorEntity(names contains "张三")
        ComparisonOperatorEntity(list contains names)
    then
        System.out.println("规则: rule_comparison_contains 触发了...");
end

// 测试比较操作符not contains
rule "rule_comparison_notcontains"
    when
        ComparisonOperatorEntity(names not contains "张三") or
        ComparisonOperatorEntity(list not contains names)
    then
        System.out.println("规则: rule_comparison_notcontains 触发了...");
end

// 测试比较操作符memberOf
rule "rule_comparison_memberOf"
    when
        ComparisonOperatorEntity(names memberOf list)
    then
        System.out.println("规则: rule_comparison_memberOf 触发了...");
end

// 测试比较操作符not memberOf
rule "rule_comparison_notmemberOf"
    when
        ComparisonOperatorEntity(names not memberOf list)
    then
        System.out.println("规则: rule_comparison_notmemberOf 触发了...");
end

// 测试比较操作符matches
rule "rule_comparison_matches"
    when
        ComparisonOperatorEntity(names matches "1张.*")
    then
        System.out.println("规则: rule_comparison_matches 触发了...");
end

// 测试比较操作not matches
rule "rule_comparison_notmatches"
    when
        ComparisonOperatorEntity(names not matches "张.*")
    then
        System.out.println("规则: rule_comparison_notmatches 触发了...");
end

// 测试操作符 not
rule "rule_comparison_not"
    when
        ComparisonOperatorEntity(!names.startsWith("张"))
    then
        System.out.println("规则: rule_comparison_not 触发了...");
end